import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
type Language = 'en' | 'tr';
interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const STORAGE_KEY = 'yok_lang_pref';
const SALT = 'yok_platform_2024';

const encodeLanguage = (lang: Language): string => {
  const data = `${lang}_${SALT}`;
  return btoa(data);
};

const decodeLanguageFromStorage = (encoded: string): Language | null => {
  try {
    const decoded = atob(encoded);
    const lang = decoded.split('_')[0] as Language;
    if (lang === 'en' || lang === 'tr') {
      return lang;
    }
  } catch (error) {
  }
  return null;
};
const translations = {
  en: {
    appTitle: 'YÖK Academic Platform',
    search: 'Search',
    dashboard: 'Dashboard',
    adminPanel: 'Admin Panel',
    login: 'Login',
    logout: 'Logout',
    user: 'User',
    findSupervisor: 'Find Your Academic Supervisor in Turkey',
    searchPlaceholder: 'Search by name...',
    searchScholars: 'Search Scholars',
    popularTopics: 'Popular Topics',
    institution: 'Institution',
    department: 'Department',
    keywords: 'Keywords',
    filters: 'Filters',
    results: 'Results',
    collaborators: 'Collaborators',
    viewProfile: 'View Profile',
    saveSearch: 'Save this Search',
    savedSearches: 'Saved Searches',
    savedSearchName: 'Search Name',
    enterSearchName: 'Enter a name for this search',
    searchSaved: 'Search saved successfully',
    searchDeleted: 'Search deleted successfully',
    failedToSaveSearch: 'Failed to save search',
    failedToDeleteSearch: 'Failed to delete search',
    failedToLoadSearches: 'Failed to load saved searches',
    noSavedSearches: 'No saved searches yet. Save your searches to access them quickly.',
    loadSavedSearch: 'Load Search',
    deleteSavedSearch: 'Delete Search',
    editSavedSearch: 'Edit Search',
    searchNameRequired: 'Search name is required',
    updateSearch: 'Update Search',
    recommendations: 'Recommended for You',
    viewCollaborationGraph: 'View Collaboration Graph',
    viewPublicationTrends: 'View Publication Trends',
    copyProfileLink: 'Copy Profile Link',
    overview: 'Overview',
    collaborationGraph: 'Collaboration Graph',
    trends: 'Trends',
    researchInterests: 'Research Interests',
    potentialDuplicates: 'Potential Duplicates',
    userEdits: 'User Edits',
    scraperStatus: 'Scraper Status',
    review: 'Review',
    approve: 'Approve',
    reject: 'Reject',
    merge: 'Merge',
    similarity: 'Similarity',
    status: 'Status',
    actions: 'Actions',
    pending: 'Pending',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    noResults: 'No results found',
    tryBroaderSearch: 'Try broader keywords or remove filters',
    signInPrompt: 'Sign in to save this search and get recommendations',
    continueWithGoogle: 'Continue with Google',
    continueWithGithub: 'Continue with GitHub',
    or: 'OR',
    oauthCallbackError: 'OAuth authentication failed',
    oauthProviderError: 'Unknown OAuth provider',
    oauthLoginSuccess: 'Authentication successful',
    completingOAuth: 'Completing authentication...',
    discoverAndConnect: 'Discover and connect with academic supervisors across Turkey',
    searchButton: 'Search',
    scholars: 'Scholars',
    institutions: 'Institutions',
    dailyUpdates: 'Daily Updates',
    daily: 'Daily',
    updates: 'Updates',
    topInstitutions: 'Top Institutions',
    exploreResearchers: 'Explore researchers and discover collaboration opportunities',
    platformFeatures: 'Platform Features',
    advancedSearch: 'Advanced Search',
    advancedSearchDesc: 'Filter by institution, department, research area, and keywords to find the perfect match with fuzzy search support',
    collaborationNetworks: 'Collaboration Networks',
    collaborationNetworksDesc: 'Visualize academic collaboration networks and discover research connections across institutions',
    aiRecommendations: 'AI Recommendations',
    aiRecommendationsDesc: 'Get personalized supervisor recommendations based on your research interests using machine learning',
    startJourney: 'Start Your Academic Journey Today',
    joinThousands: 'Join thousands of students and researchers finding their perfect academic match',
    exploreScholars: 'Explore Scholars',
    adminUser: 'Admin User',
    adminLogin: 'Admin Login',
    footerDesc: 'Empowering academic discovery in Turkey through AI-driven search and intelligent recommendations.',
    platform: 'Platform',
    home: 'Home',
    resources: 'Resources',
    documentation: 'API Reference',
    about: 'About',
    aboutUs: 'About Us',
    team: 'Team',
    contact: 'Contact',
    contactSubtitle: 'Have questions? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    sendMessage: 'Send us a Message',
    contactFormDesc: 'Fill out the form below and we\'ll get back to you within 24 hours.',
    contactName: 'Your Name',
    contactEmail: 'Your Email',
    contactSubject: 'Subject',
    contactMessage: 'Message',
    sending: 'Sending...',
    contactSuccess: 'Message sent successfully! We will get back to you soon.',
    contactError: 'Failed to send message. Please try again.',
    contactBackendError: 'We\'re having trouble connecting to our servers right now. Please try again in a few moments.',
    contactHours: 'Mon-Fri: 9:00 AM - 5:00 PM',
    contactHelp: 'Need Help?',
    contactHelpDesc1: 'Before reaching out, you might find answers to common questions in our',
    contactHelpDesc3: 'For general platform information, visit our',
    page: 'page',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    kvkkCompliance: 'KVKK Compliance',
    rightsReserved: '© 2025 Hivemind Devs - Istanbul Technical University. All rights reserved.',
    dataSourced: 'Data sourced from YÖK Akademik • Last updated: December 2025',
    academicTitle: 'Academic Title',
    allTitles: 'All Titles',
    professor: 'Professor',
    associateProfessor: 'Associate Professor',
    assistantProfessor: 'Assistant Professor',
    clearFilters: 'Clear Filters',
    searchResults: 'Search Results',
    scholarsFound: 'scholars found',
    found: 'Found',
    sortBy: 'Sort By',
    nameAsc: 'Name (A-Z)',
    nameDesc: 'Name (Z-A)',
    publicationCount: 'Publication Count',
    citations: 'Citations',
    enterSearchCriteria: 'Enter your search criteria and click the "Search" button to find scholars.',
    backendNotConnected: 'Service Temporarily Unavailable',
    backendErrorDesc: 'We\'re having trouble connecting to our servers right now. Please try again in a few moments. If the problem persists, please contact our support team.',
    noScholarsFound: 'No scholars found. Try adjusting your search criteria.',
    loginToSave: 'Please login to save scholars',
    scholarRemoved: 'Scholar removed from saved list',
    scholarSaved: 'Scholar saved successfully',
    hIndex: 'H-Index',
    pubs: 'Pubs',
    yokProfile: 'YÖK Profile',
    biography: 'Biography',
    education: 'Education',
    thesis: 'Thesis',
    academicHistory: 'Academic History',
    administrativeDuties: 'Administrative Duties',
    searchPublications: 'Search publications...',
    searchCourses: 'Search courses...',
    searchSupervisions: 'Search supervisions...',
    noPublicationsMatch: 'No publications match your search.',
    noCoursesMatch: 'No courses match your search.',
    noSupervisionsMatch: 'No supervisions match your search.',
    noPublicationsFound: 'No publications found.',
    noCoursesFound: 'No courses found.',
    noSupervisionsFound: 'No thesis supervisions found.',
    academicYear: 'Academic Year',
    courseName: 'Course Name',
    language: 'Language',
    hours: 'Hours',
    scholarNotFound: 'Scholar not found. Please check your backend connection.',
    collaborations: 'Collaborations',
    supervisions: 'Supervisions',
    courses: 'Courses',
    savedScholars: 'Saved Scholars',
    noSavedScholars: 'You haven\'t saved any scholars yet. Browse scholars and save them to your list!',
    editProfile: 'Edit Profile',
    savedDate: 'Saved: ',
    na: 'N/A',
    failedToRemoveScholar: 'Failed to remove scholar',
    noRecommendationsAvailable: 'No recommendations available. Add research interests to your profile to get personalized recommendations!',
    unknownScholar: 'Unknown Scholar',
    match: 'Match',
    matchingAreas: 'matching areas',
    searchInterests: 'Search and add research interests',
    typeToSearch: 'Type to search...',
    interestsCount: 'You can add up to 15 interests',
    noInterestsAdded: 'No research interests added yet. Search and add interests to get personalized recommendations!',
    interestAdded: 'Interest added successfully',
    interestRemoved: 'Interest removed successfully',
    failedToAddInterest: 'Failed to add interest',
    failedToRemoveInterest: 'Failed to remove interest',
    failedToLoadInterests: 'Failed to load available interests',
    maxInterestsReached: 'Maximum 15 interests allowed',
    ourTeam: 'Our Team',
    aboutTitle: 'About Hivemind',
    aboutSubtitle: 'Empowering the academic community through intelligent research discovery and collaboration',
    aboutMission: 'Our Mission',
    aboutMissionDesc1: 'The Hivemind - YÖK Academic Research Platform is dedicated to advancing Turkish academia by providing a comprehensive, intelligent platform for discovering researchers, finding supervisors, and fostering academic collaborations.',
    aboutMissionDesc2: 'We believe that connecting the right researchers can accelerate innovation and scientific progress. Our platform uses advanced search algorithms and machine learning to help students find ideal supervisors and researchers discover valuable collaboration opportunities.',
    aboutVision: 'Our Vision',
    aboutVisionDesc: 'To become the leading platform for academic discovery and collaboration in Turkey, helping shape the future of research and higher education through technology and data-driven insights.',
    aboutValues: 'Our Values',
    aboutValue1: 'Excellence in academic research',
    aboutValue2: 'Transparency and data accuracy',
    aboutValue3: 'Innovation through technology',
    aboutValue4: 'Community collaboration',
    aboutValue5: 'Ethical data practices',
    aboutTechnology: 'Technology & Innovation',
    aboutTechDesc: 'Our platform leverages cutting-edge technologies including:',
    aboutTech1: 'Machine Learning for personalized recommendations',
    aboutTech2: 'Advanced search algorithms',
    aboutTech3: 'Real-time collaboration network analysis',
    aboutTech4: 'Automated publication tracking',
    aboutTech5: 'Citation analysis and metrics',
    aboutTech6: 'Secure data management',
    meetTeamDesc: 'Meet the passionate team behind the YÖK Academic Research Platform',
    teamInfoAlert: 'Team member information will be loaded from the backend. Update team profiles in your CMS.',
    joinOurTeam: 'Join Our Team',
    joinTeamDesc: 'We\'re always looking for talented individuals passionate about advancing academic research through technology.',
    interestedJoin: 'Interested in joining us? Send your CV to ',
    projectDirector: 'Project Director',
    headOfEngineering: 'Head of Engineering',
    mlLead: 'ML & Analytics Lead',
    contentOutreach: 'Content & Outreach',
    bio1: 'Leading the vision and strategy for the platform',
    bio2: 'Building scalable and innovative solutions',
    bio3: 'Developing intelligent recommendation systems',
    bio4: 'Ensuring data quality and academic partnerships',
    back: 'Back',
    editProfileDesc: 'Update your profile information and password here',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    emailCannotBeChanged: 'Email address cannot be changed',
    changePassword: 'Change Password',
    oldPassword: 'Old Password',
    enterCurrentPassword: 'Enter your current password',
    newPassword: 'New Password',
    enterNewPassword: 'Enter your new password',
    confirmPassword: 'Confirm Password',
    confirmNewPassword: 'Enter your new password again',
    saving: 'Saving...',
    save: 'Save',
    oldPasswordRequired: 'Old password is required',
    passwordsDoNotMatch: 'New passwords do not match',
    noChangesMade: 'No changes made',
    profileUpdatedSuccess: 'Profile updated successfully!',
    profileUpdateError: 'An error occurred while updating profile',
    signUp: 'Sign Up',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Your Account',
    emailAddress: 'Email Address',
    password: 'Password',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    authFailed: 'Authentication failed. Please try again.',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    resetPasswordTitle: 'Reset Your Password',
    resetPasswordDesc: 'Enter your email address and we will send you a reset code.',
    enterResetCode: 'Enter Reset Code',
    resetCodeSent: 'A reset code has been sent to your email.',
    passwordResetSuccess: 'Password has been reset successfully. You can now login.',
    invalidCode: 'Invalid or expired code',
    sendCode: 'Send Code',
    verifyCode: 'Verify Code',
    resetPasswordButton: 'Reset Password',
    userManagement: 'User Management',
    pendingEdits: 'Pending Edits',
    duplicateManagement: 'Duplicate Management',
    activityLogs: 'Activity Logs',
    scraperJobs: 'Scraper Jobs',
    triggerScraperJobs: 'Trigger Scraper Jobs',
    scraperJobsDesc: 'These actions run in the background and may take a long time to complete.',
    starting: 'Starting...',
    loading: 'Loading...',
    scrapeUniversities: 'Scrape Universities',
    scrapeDepartments: 'Scrape Departments',
    scrapeScholars: 'Scrape Scholars',
    confirmScrapeUniversities: 'Confirm Scrape Universities',
    confirmScrapeDepartments: 'Confirm Scrape Departments',
    confirmScrapeScholars: 'Confirm Scrape Scholars',
    scrapeUniversitiesConfirm: 'Are you sure you want to scrape all universities? This process may take a long time and will run in the background.',
    scrapeDepartmentsConfirm: 'Are you sure you want to scrape all departments? This process may take a long time and will run in the background.',
    scrapeScholarsConfirm: 'Are you sure you want to scrape all scholars? This process may take a long time and will run in the background.',
    confirm: 'Confirm',
    editUser: 'Edit User',
    deleteUser: 'Delete User',
    accessDenied: 'Access denied. Admin privileges required.',
    userRoleUser: 'User',
    userRoleAdmin: 'Admin',
    statusPENDING: 'Pending',
    statusAPPROVED: 'Approved',
    statusREJECTED: 'Rejected',
    userRole: 'Role',
    active: 'Active',
    inactive: 'Inactive',
    isActive: 'Is Active',
    newPasswordOptional: 'New Password (leave empty to keep current)',
    deleteUserConfirm: 'Are you sure you want to delete this user? This action cannot be undone.',
    userUpdatedSuccess: 'User updated successfully',
    userDeletedSuccess: 'User deleted successfully',
    failedToUpdateUser: 'Failed to update user',
    failedToDeleteUser: 'Failed to delete user',
    failedToLoadUsers: 'Unable to load users. Please check your connection and ensure you have admin privileges.',
    noUsersFound: 'No users found. Ensure backend has users seeded.',
    editRequests: 'Edit Requests',
    myEditRequests: 'My Edit Requests',
    submitEditRequest: 'Submit Edit Request',
    editReason: 'Reason (Optional)',
    enterEditReason: 'Enter a reason for this edit',
    changes: 'Changes',
    submittedAt: 'Submitted At',
    reviewedBy: 'Reviewed By',
    rejectionReason: 'Rejection Reason',
    rejectReason: 'Rejection Reason',
    enterRejectReason: 'Enter a reason for rejection',
    editApproved: 'Edit request approved successfully',
    editRejected: 'Edit request rejected successfully',
    failedToApproveEdit: 'Failed to approve edit request',
    failedToRejectEdit: 'Failed to reject edit request',
    failedToLoadEdits: 'Failed to load edit requests',
    noEditRequests: 'No edit requests found',
    viewDetails: 'View Details',
    editRequestSubmitted: 'Edit request submitted successfully',
    failedToSubmitEdit: 'Failed to submit edit request',
    scholarInfo: 'Scholar Information',
    editScholarInfo: 'Edit Scholar Information',
    duplicateScholars: 'Duplicate Scholars',
    similarityScore: 'Similarity Score',
    selectForMerge: 'Select for Merge',
    mergeScholars: 'Merge Scholars',
    selectedForMerge: 'Selected for Merge',
    selectPrimaryScholar: 'Select Primary Scholar',
    primaryScholar: 'Primary Scholar',
    duplicatesToMerge: 'Duplicates to Merge',
    scholarsMerged: 'Scholars merged successfully',
    failedToMergeScholars: 'Failed to merge scholars',
    failedToLoadDuplicates: 'Failed to load duplicate scholars',
    noDuplicatesFound: 'No duplicate scholars found',
    selectDuplicatesToMerge: 'Please select duplicates to merge',
    mergeConfirmation: 'Are you sure you want to merge these scholars? This action cannot be undone.',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    failedToLoadCollaborationData: 'Failed to load collaboration data',
    noCollaborationData: 'No collaboration data available for this scholar.',
    connections: 'Connections',
    hierarchical: 'Hierarchical',
    grid: 'Grid',
    organic: 'Organic',
    pleaseEnterEmail: 'Please enter your email address',
    pleaseEnterValidCode: 'Please enter a valid 6-digit code',
    failedToSendResetCode: 'Failed to send reset code',
    failedToResetPassword: 'Failed to reset password',
    failedToUpdateSavedStatus: 'Failed to update saved status',
    pleasePerformSearch: 'Please perform a search first',
    failedToLoadSavedSearch: 'Failed to load saved search',
    failedToLoadSystemLogs: 'Failed to load system logs',
    systemActivityLogs: 'System Activity Logs',
    filterByUserId: 'Filter by user ID',
    actionType: 'Action Type',
    filterByActionType: 'Filter by action type',
    itemsPerPage: 'Items Per Page',
    failedToLoadPublicationTrends: 'Failed to load publication trends',
    userId: 'User ID',
    userIdUuid: 'User ID (UUID)',
    timestamp: 'Timestamp',
    details: 'Details',
    noLogsFound: 'No logs found.',
    publicationTrends: 'Publication Trends',
    noDataAvailable: 'No data available',
    scraperJobStarted: 'Scraper job started successfully',
    backendNotReachable: 'We\'re having trouble connecting to our servers right now. Please try again in a few moments.',
    failedToTriggerScraper: 'Failed to trigger scraper job.',
    failedToInitiateLogin: 'Failed to initiate login',
    accountNotAdmin: 'This account is not an admin.',
    accountCreatedSuccess: 'Account created successfully! Welcome',
    loginFailed: 'Login failed. Please check your credentials.',
    signupFailed: 'Signup failed. Please try again.',
    loggedOutSuccess: 'Logged out successfully!',
    failedToUpdateProfile: 'Failed to update profile. Please try again.',
    noChangesDetected: 'No changes detected',
    failedToLoadScholars: 'Failed to load scholars. Please try again.',
    kvkkComplianceNotice: 'The YÖK Academic Research Intelligence Platform is fully compliant with the Personal Data Protection Law No. 6698, which entered into force on April 7, 2016.',
    unknown: 'Unknown',
    noAuthorizationCode: 'No authorization code received',
    noAccessToken: 'No access token received from server',
    oauthAuthFailed: 'OAuth authentication failed',
    lastUpdated: 'Last Updated: December, 2025',
    termsOfServiceTitle: 'Terms of Service',
    privacyPolicyTitle: 'Privacy Policy',
    kvkkComplianceTitle: 'KVKK Compliance Notice',
    kvkkComplianceSubtitle: 'Personal Data Protection Law (KVKK) - Law No. 6698',
    stayUpdated: 'Stay Updated with New Articles',
    newsletterDesc: 'Subscribe to our weekly newsletter and never miss the latest research insights.',
    comingSoon: 'Coming soon: Email subscription feature',
    acceptingStudents: 'Accepting Students',
    available: 'Available',
    notAccepting: 'Not Accepting',
    projectManager: 'Project Manager',
    scrumMaster: 'Scrum Master',
    technicalLead: 'Technical Lead',
    crManager: 'CR Manager',
    mlAiEngineer: 'ML/AI Engineer',
    documentationManager: 'Documentation Manager',
    databaseArchitect: 'Database Architect',
    riskManager: 'Risk Manager',
    devopsEngineer: 'DevOps Engineer',
    deploymentManager: 'Deployment Manager',
    dataScrapingEngineer: 'Data Scraping Engineer',
    testingQaLead: 'Testing QA Lead',
    fullStackDeveloper: 'Full-Stack Developer',
    uiUxLead: 'UI/UX Lead',
    qaCoordinator: 'QA Coordinator',
    aboutUsTitle: 'About Us',
    aboutUsSubtitle: 'Turkey\'s most comprehensive academic research and supervisor discovery platform',
    ourMission: 'Our Mission',
    ourMissionDesc: 'Democratizing academic research in Turkey and helping graduate students find the most suitable supervisors.',
    ourMissionDesc2: 'The YÖK Academic Research Intelligence Platform brings together data from over 50,000 Turkish academics with AI-powered search and recommendation systems, making it easy for students to discover supervisors best suited to their research interests.',
    ourVision: 'Our Vision',
    ourVisionDesc: 'Providing data-driven solutions to make Turkey a world leader in academic collaboration and research ecosystem. Through our platform:',
    ourVisionPoint1: 'Students can easily find their ideal supervisors',
    ourVisionPoint2: 'Academics can discover new collaborators',
    ourVisionPoint3: 'Universities can analyze their research strengths',
    ourVisionPoint4: 'Research funding can be distributed more effectively',
    ourValues: 'Our Values',
    academicExcellence: 'Academic Excellence',
    academicExcellenceDesc: 'Enhancing research quality by providing the most current and accurate academic data.',
    innovation: 'Innovation',
    innovationDesc: 'Revolutionizing academic matching with machine learning and artificial intelligence.',
    privacyAndSecurity: 'Privacy and Security',
    privacyAndSecurityDesc: 'Protecting user data at the highest level with KVKK-compliant systems.',
    communityFocused: 'Community-Focused',
    communityFocusedDesc: 'Continuously improving by listening to academic community feedback.',
    ourStory: 'Our Story',
    ourStoryDesc1: 'The YÖK Academic Research Intelligence Platform was founded in 2024 by a group of computer engineers at Istanbul Technical University who observed the challenges students face in finding supervisors.',
    ourStoryDesc2: 'We noticed that students spent dozens of hours finding suitable supervisors, many academic profiles were outdated, and research areas were unclear. To solve this problem, we developed this platform by combining the YÖK Academic database, machine learning algorithms, and modern web technologies.',
    ourStoryDesc3: 'Today, with 50,000+ academic profiles, 500,000+ publication records, and an AI-powered recommendation system, we are Turkey\'s most comprehensive academic research platform.',
    platformByNumbers: 'Platform by Numbers',
    scholarProfiles: 'Scholar Profiles',
    universities: 'Universities',
    userSatisfaction: 'User Satisfaction'
  },
  tr: {
    appTitle: 'YÖK Akademik Platform',
    search: 'Ara',
    dashboard: 'Kullanıcı Paneli',
    adminPanel: 'Yönetici Paneli',
    login: 'Giriş Yap',
    logout: 'Çıkış Yap',
    user: 'Kullanıcı',
    findSupervisor: 'Türkiye\'de Akademik Danışmanınızı Bulun',
    searchPlaceholder: 'İsim ile arama yapın...',
    searchScholars: 'Akademisyen Ara',
    popularTopics: 'Popüler Konular',
    institution: 'Kurum',
    department: 'Bölüm',
    keywords: 'Anahtar Kelimeler',
    filters: 'Filtreler',
    results: 'Sonuçlar',
    publications: 'Yayınlar',
    collaborators: 'İşbirlikçiler',
    viewProfile: 'Profili Görüntüle',
    saveSearch: 'Aramayı Kaydet',
    savedSearches: 'Kaydedilen Aramalar',
    savedSearchName: 'Arama Adı',
    enterSearchName: 'Bu arama için bir ad girin',
    searchSaved: 'Arama başarıyla kaydedildi',
    searchDeleted: 'Arama başarıyla silindi',
    failedToSaveSearch: 'Arama kaydedilemedi',
    failedToDeleteSearch: 'Arama silinemedi',
    failedToLoadSearches: 'Kaydedilen aramalar yüklenemedi',
    noSavedSearches: 'Henüz kaydedilmiş arama yok. Aramalarınızı hızlıca erişmek için kaydedin.',
    loadSavedSearch: 'Aramayı Yükle',
    deleteSavedSearch: 'Aramayı Sil',
    editSavedSearch: 'Aramayı Düzenle',
    searchNameRequired: 'Arama adı gereklidir',
    updateSearch: 'Aramayı Güncelle',
    recommendations: 'Sizin İçin Öneriler',
    viewCollaborationGraph: 'İşbirliği Grafiğini Görüntüle',
    viewPublicationTrends: 'Yayın Trendlerini Görüntüle',
    copyProfileLink: 'Profil Bağlantısını Kopyala',
    overview: 'Genel Bakış',
    collaborationGraph: 'İşbirliği Grafiği',
    trends: 'Trendler',
    researchInterests: 'Araştırma İlgi Alanları',
    potentialDuplicates: 'Potansiyel Duplikatlar',
    userEdits: 'Kullanıcı Düzenlemeleri',
    scraperStatus: 'Veri Toplama Durumu',
    review: 'İncele',
    approve: 'Onayla',
    reject: 'Reddet',
    merge: 'Birleştir',
    similarity: 'Benzerlik',
    status: 'Durum',
    actions: 'İşlemler',
    pending: 'Beklemede',
    saveChanges: 'Değişiklikleri Kaydet',
    cancel: 'İptal',
    noResults: 'Sonuç bulunamadı',
    tryBroaderSearch: 'Daha geniş anahtar kelimeler deneyin veya filtreleri kaldırın',
    signInPrompt: 'Bu aramayı kaydetmek ve öneriler almak için giriş yapın',
    continueWithGoogle: 'Google ile Devam Et',
    continueWithGithub: 'GitHub ile Devam Et',
    or: 'VEYA',
    oauthCallbackError: 'OAuth kimlik doğrulaması başarısız',
    oauthProviderError: 'Bilinmeyen OAuth sağlayıcı',
    oauthLoginSuccess: 'Kimlik doğrulaması başarılı',
    completingOAuth: 'Kimlik doğrulaması tamamlanıyor...',
    discoverAndConnect: 'Türkiye genelindeki akademik danışmanları keşfedin ve onlarla bağlantı kurun',
    searchButton: 'Ara',
    scholars: 'Akademisyenler',
    institutions: 'Kurumlar',
    dailyUpdates: 'Günlük Güncellemeler',
    daily: 'Günlük',
    updates: 'Güncellemeler',
    topInstitutions: 'Önde Gelen Kurumlar',
    exploreResearchers: 'Araştırmacıları keşfedin ve işbirliği fırsatlarını yakalayın',
    platformFeatures: 'Platform Özellikleri',
    advancedSearch: 'Gelişmiş Arama',
    advancedSearchDesc: 'Kurum, bölüm, araştırma alanı ve anahtar kelimelere göre filtreleme yaparak mükemmel eşleşmeyi bulan bulanık arama desteği',
    collaborationNetworks: 'İşbirliği Ağları',
    collaborationNetworksDesc: 'Akademik işbirliği ağlarını görselleştirin ve kurumlar arası araştırma bağlantılarını keşfedin',
    aiRecommendations: 'Yapay Zeka Önerileri',
    aiRecommendationsDesc: 'Makine öğrenimi kullanarak araştırma ilgi alanlarınıza göre kişiselleştirilmiş danışman önerileri alın',
    startJourney: 'Akademik Yolculuğunuza Bugün Başlayın',
    joinThousands: 'Mükemmel akademik eşleşmelerini bulan binlerce öğrenci ve araştırmacıya katılın',
    exploreScholars: 'Akademisyenleri Keşfet',
    adminUser: 'Yönetici Kullanıcı',
    adminLogin: 'Yönetici Girişi',
    footerDesc: 'Yapay zeka destekli arama ve akıllı önerilerle Türkiye\'deki akademik keşifleri güçlendiriyoruz.',
    platform: 'Platform',
    home: 'Ana Sayfa',
    resources: 'Kaynaklar',
    documentation: 'API Referansı',
    about: 'Hakkında',
    aboutUs: 'Hakkımızda',
    team: 'Takım',
    contact: 'İletişim',
    contactSubtitle: 'Sorularınız mı var? Sizden haber almak isteriz. Bize mesaj gönderin, en kısa sürede size dönüş yapacağız.',
    email: 'E-posta',
    phone: 'Telefon',
    address: 'Adres',
    sendMessage: 'Bize Mesaj Gönderin',
    contactFormDesc: 'Aşağıdaki formu doldurun, 24 saat içinde size geri dönüş yapacağız.',
    contactName: 'Adınız',
    contactEmail: 'E-posta Adresiniz',
    contactSubject: 'Konu',
    contactMessage: 'Mesajınız',
    sending: 'Gönderiliyor...',
    contactSuccess: 'Mesajınız başarıyla gönderildi! En kısa sürede size dönüş yapacağız.',
    contactError: 'Mesaj gönderilemedi. Lütfen tekrar deneyin.',
    contactBackendError: 'Şu anda sunucularımıza bağlanmakta sorun yaşıyoruz. Lütfen birkaç dakika sonra tekrar deneyin.',
    contactHours: 'Pazartesi-Cuma: 09:00 - 17:00',
    contactHelp: 'Yardıma mı İhtiyacınız Var?',
    contactHelpDesc1: 'Bize ulaşmadan önce, sık sorulan sorulara yanıtları',
    contactHelpDesc3: 'Genel platform bilgileri için',
    page: 'sayfasını',
    legal: 'Yasal',
    privacyPolicy: 'Gizlilik Politikası',
    termsOfService: 'Hizmet Şartları',
    kvkkCompliance: 'KVKK Uyumluluğu',
    rightsReserved: '© 2025 Hivemind Devs - İstanbul Teknik Üniversitesi. Tüm hakları saklıdır.',
    dataSourced: 'Veriler YÖK Akademik\'ten alınmıştır • Son güncelleme: Aralık 2025',
    academicTitle: 'Akademik Unvan',
    allTitles: 'Tüm Unvanlar',
    professor: 'Profesör',
    associateProfessor: 'Doçent',
    assistantProfessor: 'Doktor Öğretim Üyesi',
    clearFilters: 'Filtreleri Temizle',
    searchResults: 'Arama Sonuçları',
    scholarsFound: 'akademisyen bulundu',
    found: '',
    sortBy: 'Sıralama',
    nameAsc: 'İsim (A-Z)',
    nameDesc: 'İsim (Z-A)',
    publicationCount: 'Yayın Sayısı',
    citations: 'Atıflar',
    enterSearchCriteria: 'Akademisyenleri bulmak için arama kriterlerinizi girin ve "Ara" butonuna tıklayın.',
    backendNotConnected: 'Hizmet Geçici Olarak Kullanılamıyor',
    backendErrorDesc: 'Şu anda sunucularımıza bağlanmakta sorun yaşıyoruz. Lütfen birkaç dakika sonra tekrar deneyin. Sorun devam ederse, destek ekibimizle iletişime geçebilirsiniz.',
    noScholarsFound: 'Akademisyen bulunamadı. Arama kriterlerinizi değiştirmeyi deneyin.',
    loginToSave: 'Akademisyenleri kaydetmek için lütfen giriş yapın',
    scholarRemoved: 'Akademisyen kaydedilenler listesinden çıkarıldı',
    scholarSaved: 'Akademisyen başarıyla kaydedildi',
    hIndex: 'H-İndeksi',
    pubs: 'Yayınlar',
    yokProfile: 'YÖK Profili',
    biography: 'Biyografi',
    education: 'Eğitim',
    thesis: 'Tez',
    academicHistory: 'Akademik Geçmiş',
    administrativeDuties: 'İdari Görevler',
    searchPublications: 'Yayınlarda ara...',
    searchCourses: 'Derslerde ara...',
    searchSupervisions: 'Tezlerde ara...',
    noPublicationsMatch: 'Aramanızla eşleşen yayın bulunamadı.',
    noCoursesMatch: 'Aramanızla eşleşen ders bulunamadı.',
    noSupervisionsMatch: 'Aramanızla eşleşen tez bulunamadı.',
    noPublicationsFound: 'Yayın bulunamadı.',
    noCoursesFound: 'Ders bulunamadı.',
    noSupervisionsFound: 'Tez danışmanlığı bulunamadı.',
    academicYear: 'Akademik Yıl',
    courseName: 'Ders Adı',
    language: 'Dil',
    hours: 'Saat',
    scholarNotFound: 'Akademisyen bulunamadı. Lütfen backend bağlantınızı kontrol edin.',
    collaborations: 'İşbirlikleri',
    supervisions: 'Danışmanlıklar',
    courses: 'Dersler',
    savedScholars: 'Kaydedilen Akademisyenler',
    noSavedScholars: 'Henüz kaydedilmiş bir akademisyeniniz yok. Akademisyenleri inceleyin ve listenize kaydedin!',
    editProfile: 'Profili Düzenle',
    savedDate: 'Kaydedildi: ',
    na: 'Yok',
    failedToRemoveScholar: 'Akademisyen kaldırılamadı',
    noRecommendationsAvailable: 'Öneri bulunmuyor. Kişiselleştirilmiş öneriler almak için profil bilgilerinize araştırma ilgi alanlarınızı ekleyin!',
    unknownScholar: 'Bilinmeyen Akademisyen',
    match: 'Eşleşme',
    matchingAreas: 'eşleşen alan',
    searchInterests: 'Araştırma ilgi alanlarını ara ve ekle',
    typeToSearch: 'Aramak için yazın...',
    interestsCount: 'Maksimum 15 ilgi alanı ekleyebilirsiniz',
    noInterestsAdded: 'Henüz araştırma ilgi alanı eklenmedi. Kişiselleştirilmiş öneriler almak için ilgi alanlarınızı arayın ve ekleyin!',
    interestAdded: 'İlgi alanı başarıyla eklendi',
    interestRemoved: 'İlgi alanı başarıyla kaldırıldı',
    failedToAddInterest: 'İlgi alanı eklenemedi',
    failedToRemoveInterest: 'İlgi alanı kaldırılamadı',
    failedToLoadInterests: 'Mevcut ilgi alanları yüklenemedi',
    maxInterestsReached: 'Maksimum 15 ilgi alanına ulaşıldı',
    ourTeam: 'Ekibimiz',
    aboutTitle: 'Hivemind Hakkında',
    aboutSubtitle: 'Akademik topluluğu akıllı araştırma keşfi ve işbirliği ile güçlendiriyoruz',
    aboutMission: 'Misyonumuz',
    aboutMissionDesc1: 'Hivemind - YÖK Akademik Araştırma Platformu, araştırmacıları keşfetmek, danışman bulmak ve akademik işbirliklerini geliştirmek için kapsamlı ve akıllı bir platform sağlayarak Türk akademisini ilerletmeye adanmıştır.',
    aboutMissionDesc2: 'Doğru araştırmacıları bir araya getirmenin yeniliği ve bilimsel ilerlemeyi hızlandırabileceğine inanıyoruz. Platformumuz, öğrencilerin ideal danışmanlarını bulmalarına ve araştırmacıların değerli işbirliği fırsatlarını keşfetmelerine yardımcı olmak için gelişmiş arama algoritmaları ve makine öğrenimi kullanır.',
    aboutVision: 'Vizyonumuz',
    aboutVisionDesc: 'Türkiye\'de akademik keşif ve işbirliği için önde gelen platform haline gelmek, teknoloji ve veri odaklı içgörüler aracılığıyla araştırma ve yükseköğretimin geleceğini şekillendirmeye yardımcı olmak.',
    aboutValues: 'Değerlerimiz',
    aboutValue1: 'Akademik araştırmada mükemmellik',
    aboutValue2: 'Şeffaflık ve veri doğruluğu',
    aboutValue3: 'Teknoloji ile yenilik',
    aboutValue4: 'Topluluk işbirliği',
    aboutValue5: 'Etik veri uygulamaları',
    aboutTechnology: 'Teknoloji & Yenilik',
    aboutTechDesc: 'Platformumuz aşağıdaki son teknoloji teknolojilerden yararlanır:',
    aboutTech1: 'Kişiselleştirilmiş öneriler için Makine Öğrenimi',
    aboutTech2: 'Gelişmiş arama algoritmaları',
    aboutTech3: 'Gerçek zamanlı işbirliği ağı analizi',
    aboutTech4: 'Otomatik yayın takibi',
    aboutTech5: 'Atıf analizi ve metrikleri',
    aboutTech6: 'Güvenli veri yönetimi',
    meetTeamDesc: 'YÖK Akademik Araştırma Platformu arkasındaki tutkulu ekiple tanışın',
    teamInfoAlert: 'Ekip üyesi bilgileri backendden yüklenecektir. CMS üzerinden ekip profillerini güncelleyin.',
    joinOurTeam: 'Ekibimize Katılın',
    joinTeamDesc: 'Teknoloji yoluyla akademik araştırmayı ilerletme konusunda tutkulu yetenekli bireyler arıyoruz.',
    interestedJoin: 'Bize katılmak ister misiniz? CV\'nizi gönderin: ',
    projectDirector: 'Proje Direktörü',
    headOfEngineering: 'Mühendislik Başkanı',
    mlLead: 'ML & Analitik Lideri',
    contentOutreach: 'İçerik & İletişim',
    bio1: 'Platform için vizyon ve stratejiye liderlik ediyor',
    bio2: 'Ölçeklenebilir ve yenilikçi çözümler geliştiriyor',
    bio3: 'Akıllı öneri sistemleri geliştiriyor',
    bio4: 'Veri kalitesini ve akademik işbirliklerini sağlıyor',
    back: 'Geri Dön',
    editProfileDesc: 'Profil bilgilerinizi ve şifrenizi buradan güncelleyebilirsiniz',
    fullName: 'Ad Soyad',
    enterFullName: 'Adınızı ve soyadınızı girin',
    emailCannotBeChanged: 'E-posta adresi değiştirilemez',
    changePassword: 'Şifre Değiştir',
    oldPassword: 'Eski Şifre',
    enterCurrentPassword: 'Mevcut şifrenizi girin',
    newPassword: 'Yeni Şifre',
    enterNewPassword: 'Yeni şifrenizi girin',
    confirmPassword: 'Yeni Şifre Tekrar',
    confirmNewPassword: 'Yeni şifrenizi tekrar girin',
    saving: 'Kaydediliyor...',
    save: 'Kaydet',
    oldPasswordRequired: 'Eski şifre gereklidir',
    passwordsDoNotMatch: 'Yeni şifreler eşleşmiyor',
    noChangesMade: 'Değişiklik yapılmadı',
    profileUpdatedSuccess: 'Profil başarıyla güncellendi!',
    profileUpdateError: 'Profil güncellenirken bir hata oluştu',
    signUp: 'Kayıt Ol',
    welcomeBack: 'Tekrar Hoş Geldiniz',
    createAccount: 'Hesabınızı Oluşturun',
    emailAddress: 'E-posta Adresi',
    password: 'Şifre',
    enterEmail: 'E-posta adresinizi girin',
    enterPassword: 'Şifrenizi girin',
    authFailed: 'Kimlik doğrulama başarısız oldu. Lütfen tekrar deneyin.',
    forgotPassword: 'Şifremi Unuttum',
    resetPassword: 'Şifre Sıfırla',
    resetPasswordTitle: 'Şifrenizi Sıfırlayın',
    resetPasswordDesc: 'E-posta adresinizi girin, size sıfırlama kodu göndereceğiz.',
    enterResetCode: 'Sıfırlama Kodunu Girin',
    resetCodeSent: 'E-posta adresinize bir sıfırlama kodu gönderildi.',
    passwordResetSuccess: 'Şifre başarıyla sıfırlandı. Şimdi giriş yapabilirsiniz.',
    invalidCode: 'Geçersiz veya süresi dolmuş kod',
    sendCode: 'Kodu Gönder',
    verifyCode: 'Kodu Doğrula',
    resetPasswordButton: 'Şifreyi Sıfırla',
    userManagement: 'Kullanıcı Yönetimi',
    pendingEdits: 'Bekleyen Düzenlemeler',
    duplicateManagement: 'Yinelenen Yönetimi',
    activityLogs: 'Aktivite Günlükleri',
    scraperJobs: 'Tarama İşleri',
    triggerScraperJobs: 'Tarama İşlerini Tetikle',
    scraperJobsDesc: 'Bu işlemler arka planda çalışır ve tamamlanması uzun sürebilir.',
    starting: 'Başlatılıyor...',
    loading: 'Yükleniyor...',
    scrapeUniversities: 'Üniversiteleri Çek',
    scrapeDepartments: 'Departmanları Çek',
    scrapeScholars: 'Akademisyenleri Çek',
    confirmScrapeUniversities: 'Üniversiteleri Çekmeyi Onayla',
    confirmScrapeDepartments: 'Departmanları Çekmeyi Onayla',
    confirmScrapeScholars: 'Akademisyenleri Çekmeyi Onayla',
    scrapeUniversitiesConfirm: 'Tüm üniversiteleri çekmek istediğinizden emin misiniz? Bu işlem uzun sürebilir ve arka planda çalışacaktır.',
    scrapeDepartmentsConfirm: 'Tüm departmanları çekmek istediğinizden emin misiniz? Bu işlem uzun sürebilir ve arka planda çalışacaktır.',
    scrapeScholarsConfirm: 'Tüm akademisyenleri çekmek istediğinizden emin misiniz? Bu işlem uzun sürebilir ve arka planda çalışacaktır.',
    confirm: 'Onayla',
    editUser: 'Kullanıcı Düzenle',
    deleteUser: 'Kullanıcı Sil',
    accessDenied: 'Erişim reddedildi. Yönetici yetkisi gereklidir.',
    userRoleUser: 'Kullanıcı',
    userRoleAdmin: 'Yönetici',
    statusPENDING: 'Beklemede',
    statusAPPROVED: 'Onaylandı',
    statusREJECTED: 'Reddedildi',
    userRole: 'Rol',
    active: 'Aktif',
    inactive: 'Pasif',
    isActive: 'Aktif mi',
    newPasswordOptional: 'Yeni Şifre (mevcut şifreyi korumak için boş bırakın)',
    deleteUserConfirm: 'Bu kullanıcıyı silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    userUpdatedSuccess: 'Kullanıcı başarıyla güncellendi',
    userDeletedSuccess: 'Kullanıcı başarıyla silindi',
    failedToUpdateUser: 'Kullanıcı güncellenemedi',
    failedToDeleteUser: 'Kullanıcı silinemedi',
    failedToLoadUsers: 'Kullanıcılar yüklenemedi. Lütfen bağlantınızı kontrol edin ve yönetici yetkiniz olduğundan emin olun.',
    noUsersFound: 'Kullanıcı bulunamadı. Sistemde kullanıcıların olduğundan emin olun.',
    editRequests: 'Düzenleme İstekleri',
    myEditRequests: 'Düzenleme İsteklerim',
    submitEditRequest: 'Düzenleme İsteği Gönder',
    editReason: 'Gerekçe (Opsiyonel)',
    enterEditReason: 'Bu düzenleme için bir gerekçe girin',
    changes: 'Değişiklikler',
    submittedAt: 'Gönderilme Tarihi',
    reviewedBy: 'İnceleyen',
    rejectionReason: 'Red Nedeni',
    rejectReason: 'Red Nedeni',
    enterRejectReason: 'Red nedeni girin',
    editApproved: 'Düzenleme isteği başarıyla onaylandı',
    editRejected: 'Düzenleme isteği başarıyla reddedildi',
    failedToApproveEdit: 'Düzenleme isteği onaylanamadı',
    failedToRejectEdit: 'Düzenleme isteği reddedilemedi',
    failedToLoadEdits: 'Düzenleme istekleri yüklenemedi',
    noEditRequests: 'Düzenleme isteği bulunamadı',
    viewDetails: 'Detayları Görüntüle',
    editRequestSubmitted: 'Düzenleme isteği başarıyla gönderildi',
    failedToSubmitEdit: 'Düzenleme isteği gönderilemedi',
    scholarInfo: 'Akademisyen Bilgileri',
    editScholarInfo: 'Akademisyen Bilgilerini Düzenle',
    duplicateScholars: 'Yinelenen Akademisyenler',
    similarityScore: 'Benzerlik Skoru',
    selectForMerge: 'Birleştirme İçin Seç',
    mergeScholars: 'Akademisyenleri Birleştir',
    selectedForMerge: 'Birleştirme İçin Seçilenler',
    selectPrimaryScholar: 'Ana Akademisyeni Seç',
    primaryScholar: 'Ana Akademisyen',
    duplicatesToMerge: 'Birleştirilecek Yinelenenler',
    scholarsMerged: 'Akademisyenler başarıyla birleştirildi',
    failedToMergeScholars: 'Akademisyenler birleştirilemedi',
    failedToLoadDuplicates: 'Yinelenen akademisyenler yüklenemedi',
    noDuplicatesFound: 'Yinelenen akademisyen bulunamadı',
    selectDuplicatesToMerge: 'Lütfen birleştirmek için yinelenenleri seçin',
    mergeConfirmation: 'Bu akademisyenleri birleştirmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    selectAll: 'Tümünü Seç',
    deselectAll: 'Seçimi Kaldır',
    failedToLoadCollaborationData: 'İşbirliği verileri yüklenemedi',
    noCollaborationData: 'Bu akademisyen için işbirliği verisi bulunmuyor.',
    connections: 'Bağlantılar',
    hierarchical: 'Hiyerarşik',
    grid: 'Izgara',
    organic: 'Organik',
    pleaseEnterEmail: 'Lütfen e-posta adresinizi girin',
    pleaseEnterValidCode: 'Lütfen geçerli bir 6 haneli kod girin',
    failedToSendResetCode: 'Sıfırlama kodu gönderilemedi',
    failedToResetPassword: 'Şifre sıfırlanamadı',
    failedToUpdateSavedStatus: 'Kaydedilme durumu güncellenemedi',
    pleasePerformSearch: 'Lütfen önce bir arama yapın',
    failedToLoadSavedSearch: 'Kaydedilen arama yüklenemedi',
    failedToLoadSystemLogs: 'Sistem günlükleri yüklenemedi',
    systemActivityLogs: 'Sistem Aktivite Günlükleri',
    filterByUserId: 'Kullanıcı ID\'sine göre filtrele',
    actionType: 'İşlem Türü',
    filterByActionType: 'İşlem türüne göre filtrele',
    itemsPerPage: 'Sayfa Başına Öğe',
    failedToLoadPublicationTrends: 'Yayın trendleri yüklenemedi',
    userId: 'Kullanıcı ID',
    userIdUuid: 'Kullanıcı ID (UUID)',
    timestamp: 'Zaman Damgası',
    details: 'Detaylar',
    noLogsFound: 'Günlük bulunamadı.',
    publicationTrends: 'Yayın Trendleri',
    noDataAvailable: 'Veri bulunamadı',
    scraperJobStarted: 'Tarama işi başarıyla başlatıldı',
    backendNotReachable: 'Şu anda sunucularımıza bağlanmakta sorun yaşıyoruz. Lütfen birkaç dakika sonra tekrar deneyin.',
    failedToTriggerScraper: 'Tarama işi tetiklenemedi.',
    failedToInitiateLogin: 'Giriş başlatılamadı',
    accountNotAdmin: 'Bu hesap bir yönetici değil.',
    accountCreatedSuccess: 'Hesap başarıyla oluşturuldu! Hoş geldiniz',
    loginFailed: 'Giriş başarısız oldu. Lütfen kimlik bilgilerinizi kontrol edin.',
    signupFailed: 'Kayıt başarısız oldu. Lütfen tekrar deneyin.',
    loggedOutSuccess: 'Başarıyla çıkış yapıldı!',
    failedToUpdateProfile: 'Profil güncellenemedi. Lütfen tekrar deneyin.',
    noChangesDetected: 'Değişiklik tespit edilmedi',
    failedToLoadScholars: 'Akademisyenler yüklenemedi. Lütfen tekrar deneyin.',
    kvkkComplianceNotice: 'YÖK Akademik Araştırma İstihbarat Platformu, 7 Nisan 2016 tarihinde yürürlüğe giren 6698 sayılı Kişisel Verilerin Korunması Kanunu\'na tam uyumluluk sağlamaktadır.',
    unknown: 'Bilinmeyen',
    noAuthorizationCode: 'Yetkilendirme kodu alınamadı',
    noAccessToken: 'Sunucudan erişim token\'ı alınamadı',
    oauthAuthFailed: 'OAuth kimlik doğrulaması başarısız',
    lastUpdated: 'Son Güncelleme: Aralık 2025',
    termsOfServiceTitle: 'Kullanım Koşulları',
    privacyPolicyTitle: 'Gizlilik Politikası',
    kvkkComplianceTitle: 'KVKK Uyumluluk Bildirimi',
    kvkkComplianceSubtitle: 'Kişisel Verilerin Korunması Kanunu (KVKK) - 6698 Sayılı Kanun',
    stayUpdated: 'Yeni Makalelerden Haberdar Olun',
    newsletterDesc: 'Haftalık bültenimize abone olun ve en son araştırma içgörülerini kaçırmayın.',
    comingSoon: 'Yakında: E-posta abonelik özelliği',
    acceptingStudents: 'Öğrenci Kabul Ediyor',
    available: 'Müsait',
    notAccepting: 'Kabul Etmiyor',
    projectManager: 'Proje Yöneticisi',
    scrumMaster: 'Scrum Master',
    technicalLead: 'Teknik Lider',
    crManager: 'CR Yöneticisi',
    mlAiEngineer: 'ML/AI Mühendisi',
    documentationManager: 'Dokümantasyon Yöneticisi',
    databaseArchitect: 'Veritabanı Mimarı',
    riskManager: 'Risk Yöneticisi',
    devopsEngineer: 'DevOps Mühendisi',
    deploymentManager: 'Dağıtım Yöneticisi',
    dataScrapingEngineer: 'Veri Toplama Mühendisi',
    testingQaLead: 'Test QA Lideri',
    fullStackDeveloper: 'Full-Stack Geliştirici',
    uiUxLead: 'UI/UX Lideri',
    qaCoordinator: 'QA Koordinatörü',
    aboutUsTitle: 'Hakkımızda',
    aboutUsSubtitle: 'Türkiye\'nin en kapsamlı akademik araştırma ve danışman bulma platformu',
    ourMission: 'Misyonumuz',
    ourMissionDesc: 'Türkiye\'deki akademik araştırmayı demokratikleştirmek ve yüksek lisans/doktora öğrencilerinin en uygun danışmanları bulmalarını sağlamak.',
    ourMissionDesc2: 'YÖK Akademik Araştırma İstihbarat Platformu, yapay zeka destekli arama ve öneri sistemleriyle 50,000\'den fazla Türk akademisyenin verisini bir araya getirerek, öğrencilerin araştırma ilgi alanlarına en uygun danışmanları keşfetmelerini kolaylaştırır.',
    ourVision: 'Vizyonumuz',
    ourVisionDesc: 'Türkiye\'yi akademik işbirliği ve araştırma ekosisteminde dünya lideri yapmak için veri odaklı çözümler sunmak. Platform\'umuz sayesinde:',
    ourVisionPoint1: 'Öğrenciler ideal danışmanlarını kolayca bulabilir',
    ourVisionPoint2: 'Akademisyenler yeni işbirlikçiler keşfedebilir',
    ourVisionPoint3: 'Üniversiteler araştırma güçlerini analiz edebilir',
    ourVisionPoint4: 'Araştırma fonları daha etkili dağıtılabilir',
    ourValues: 'Değerlerimiz',
    academicExcellence: 'Akademik Mükemmellik',
    academicExcellenceDesc: 'En güncel ve doğru akademik verileri sunarak araştırma kalitesini artırıyoruz.',
    innovation: 'Yenilikçilik',
    innovationDesc: 'Makine öğrenmesi ve yapay zeka ile akademik eşleştirmede devrim yaratıyoruz.',
    privacyAndSecurity: 'Gizlilik ve Güvenlik',
    privacyAndSecurityDesc: 'KVKK uyumlu sistemlerimizle kullanıcı verilerini en üst düzeyde koruyoruz.',
    communityFocused: 'Topluluk Odaklı',
    communityFocusedDesc: 'Akademik topluluğun geri bildirimlerini dinleyerek sürekli gelişiyoruz.',
    ourStory: 'Hikayemiz',
    ourStoryDesc1: 'YÖK Akademik Araştırma İstihbarat Platformu, İstanbul Teknik Üniversitesi\'nde öğrencilerin danışman bulma sürecindeki zorluklarını gözlemleyen bir grup bilgisayar mühendisi tarafından 2024 yılında kuruldu.',
    ourStoryDesc2: 'Öğrencilerin uygun danışman bulmak için onlarca saat harcadığını, birçok akademisyenin profilinin güncel olmadığını ve araştırma alanlarının net olmadığını fark ettik. Bu sorunu çözmek için YÖK Akademik veritabanını, makine öğrenmesi algoritmalarını ve modern web teknolojilerini bir araya getirerek bu platformu geliştirdik.',
    ourStoryDesc3: 'Bugün, 50,000+ akademisyen profili, 500,000+ yayınlar ve yapay zeka destekli öneri sistemiyle Türkiye\'nin en kapsamlı akademik araştırma platformuyuz.',
    platformByNumbers: 'Rakamlarla Platform',
    scholarProfiles: 'Akademisyen Profili',
    universities: 'Üniversite',
    userSatisfaction: 'Kullanıcı Memnuniyeti'
  }
};
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const getInitialLanguage = (): Language => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored) {
        const decoded = decodeLanguageFromStorage(stored);
        if (decoded) {
          return decoded;
        }
      }
    } catch (error) {
      console.error('Error reading language preference:', error);
    }
    return 'en';
  };

  const [language, setLanguage] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    try {
      const encoded = encodeLanguage(language);
      localStorage.setItem(STORAGE_KEY, encoded);
    } catch (error) {
      console.error('Error saving language preference:', error);
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => {
      const newLang = prev === 'en' ? 'tr' : 'en';
      try {
        const encoded = encodeLanguage(newLang);
        localStorage.setItem(STORAGE_KEY, encoded);
      } catch (error) {
        console.error('Error saving language preference:', error);
      }
      return newLang;
    });
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};